### ISSUE TITLE
Doesn't show "not Hitler confirmed"

### ISSUE THREAD

**Issue by pasmai** [kylecoburn/secret-hitler#16]
when a chancelor is succesfully elected in the red zone it doesn't mark them as "not Hitler".

**Comment by thaiduynguyen** [comment]
I also think a "Not Hitler" tag would be helpful. The Secret Hitler mod for Tabletop Simulator has a Not Hitler card so I think this site should have it too. The Not Hitler tag should be applied to chancellors who were elected after 3 fascists policies and dead players.

**Comment by MathSquared** [comment]
I think the designers have said it's intentional not to include a CNH tag. That's because not tracking it lets the fascists take advantage of liberals' faulty memories and fool them as to who is CNH.

Not sure how well that reasoning holds up online, though, when someone can keep a paper notepad. At least I think the automation or not of CNH tags should be configurable in custom games.

**Comment by pasmai** [comment]
I will close this since the design decision is up to the creator.
