### ISSUE TITLE
Misattribution

### ISSUE THREAD

**Issue by tommygents** [kylecoburn/secret-hitler#8]
Hey dude! I found a couple problems with the landing page of secrethitler.online: 

- contains no link back to secrethitler.com.
- contains link to wrong Creative Commons license
- It shouldn't describe the code as "open source," since the CC-BY-NC-SA 4.0 license isn't an open source license, and this implementation contains covered assets.

I can see from your source code there's supposed to be a feedback option in the page but clicking on the sword/wreath on the bottom right doesn't do anything. This is literally the only way I could find to contact you and let you know about those issues.

Let me know if you have questions, here or at secrethitlergame@gmail.com.
-Tommy Maranges

**Comment by kylecoburn** [comment]
Thanks for reporting these issues Tommy, sorry it's not up to scratch; I hardly ever look at the landing page since I'm always signed in.

GitHub issues is the only place to discuss the project (the feedback form you're talking about is really intended for playtesting feedback), so no problems there.

- Contains no link back to secrethitler.com
This was a copy paste error (of course the Secret Hitler text was intended to link to secrethitler.com rather than redundantly linking the license page). FYI, it is also linked to in the about section of the game menu. Fixed, thank you.

- contains link to wrong Creative Commons license
This page was authored before you guys had stated the exact CC license, so all I could do was guess at that time (the readme file was updated, but unfortunately I forgot about that other reference). Updated, thank you.

- It shouldn't describe the code as "open source,"
The code is open source in that anyone download/copy it, that is my own definition and evidently not any kind of legal claim (note how there is no additional license governing the code, mainly because I don't understand CC well enough to know how to go about that). If you need me to clarify any further how the game itself falls under CC, let me know.

If you were looking for a direct line of communication though, I did attempt to contact you guys what would have been months ago (December I think?) now to seek any feedback/permission from you guys before releasing this. That would have been helpful for me too!
